// <auto-generated />
namespace LeThanhLong_DoAn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class themrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(themrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202211301315156_them-required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
